[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { version = "1.18.0", features = ["v6"] }

[dev-dependencies]
tokio = { workspace = true }