# Note: version is obsolete in newer Docker Compose versions

services:
  html-api-reader:
    build:
      context: .
      dockerfile: Dockerfile
    image: html-api-reader:latest
    container_name: html-api-reader
    restart: unless-stopped
    ports:
      - "8085:8085"
    
    # Environment variables
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - PORT=8085
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # If your application needs to communicate with other services
    # networks:
    #   - mcp-network
    
    # If you need persistent storage
    # volumes:
    #   - ./data:/app/data
    
    # REST API doesn't need stdin/stdout interaction
    # stdin_open: true
    # tty: true
    
    # Labels for better organization
    labels:
      - "com.example.description=HTML API Reader - REST API server for web content fetching"
      - "com.example.version=0.1.0"
      - "com.example.component=api-server"

# If you need a custom network
# networks:
#   mcp-network:
#     driver: bridge

# If you need volumes for persistent data
# volumes:
#   app-data: